# -*- coding: utf-8 -*-
"""wsgi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5q1HAeepP4F06w8L6BbrrbVCudqvWBa
"""

from app.main import app
if __name__ == "__main__":
  app.run()